[package]
name = "spawning-drunagor"
version = "0.5.2"
authors = ["ALeX Kazik <alex@kazik.de>"]
edition = "2024"
license = "MIT"

[dependencies]
enum-tools = { version = "0.5", default-features = false }
getrandom = { version = "0.4.1", default-features = false, features = ["wasm_js"] }
rand = { version = "0.10.0", default-features = false, features = ["sys_rng"] }
serde = { version = "1", default-features = false, features = ["serde_derive"] }
serde-wasm-bindgen = { version = "0.6", default-features = false, optional = true }
serde_repr = { version = "0.1", default-features = false }
typed-i18n = { version = "0.6.2" }
web-sys = { version = "0.3", default-features = false, features = ["HtmlTextAreaElement", "HtmlSelectElement"], optional = true }
yew = { version = "0.22", default-features = false, features = ["csr"] }
yew-bootstrap = { version = "0.14", default-features = false }
yewdux = { version = "0.12.0", default-features = false }

[build-dependencies]
anyhow = "1.0.101"
generator = { path = "generator" }

[features]
default = ["debug"]
debug = ["dep:serde-wasm-bindgen", "dep:web-sys"]

[[bin]]
name = "copy-and-link"

[lints.clippy]
std_instead_of_core = "warn"
pedantic = { level = "warn", priority = -1 }
missing_errors_doc = "allow"
module_name_repetitions = "allow"
similar_names = "allow"
too_many_lines = "allow"
unsafe_derive_deserialize = "allow"

[workspace]
members = [
    ".",
    "generator",
]
